// function, that counts everything

export default function makeStats(lyrics) {
  function countWordsArray(words, texts) {
    let count = 0
    function countWords(word, string) {
      const regexp = new RegExp(`\\b${word}\\b`, 'gim')
      const result = string.match(regexp)?.length
      if (result === undefined) {
        return 0
      } return result
    }
    for (let i = 0; i < texts.length; i += 1) {
      for (let j = 0; j < words.length; j += 1) {
        const num = countWords(words[j], texts[i])
        count += num
      }
    }
    return count
  }

  // COLORS

  const red = [
    'fire',
    'tomato',
    'maroon',
    'cardinal',
    'coral',
    'crimson',
    'flaming',
    'maroon',
    'rose',
    'wine',
    'blush',
    'burgundy',
    'cerise',
    'cherry',
    'claret',
    'garnet',
    'infrared',
    'magenta',
    'pink',
    'ruby',
    'russet',
    'salmon',
    'sanguine',
    'scarlet',
    'vermilion',
    'bloodshot',
    'flushed',
    'healthy',
    'inflamed',
    'roseate',
    'rosy',
    'rubicund',
    'ruddy',
    'raspberry',
    'lava',
  ]

  const green = [
    'chartreuse',
    'lime',
    'green',
    'olive',
    'avocado',
    'pistachio',
    'jungle',
    'forest',
    'mint',
    'lawn',
    'malachite',
    'emerald',
    'celadon',
  ]

  const blue = [
    'turquoise',
    'celeste',
    'ultramarine',
    'sapphire',
    'cornflower',
    'azure',
    'navy',
    'aqua',
    'denim',
    'blizzard',
    'blue',
    'cyan',
    'ocean',
    'sky',
  ]

  const yellow = [
    'yellow',
    'lemon',
    'curry',
    'mustard',
    'beige',
    'amber',
    'honey',
    'banana',
    'peach',
    'wheat',
    'butter',
    'blond',
    'sunflower',
    'sand',
    'gold',
    'golden',
    'sun',
    'corn',
    'khaki',
  ]

  const orange = [
    'pumpkin',
    'carrot',
    'orange',
    'bronze',
  ]

  const purple = [
    'purple',
    'lavender',
    'plum',
    'eggplant',
    'orchid',
    'violet',
    'iris',
    'lilac',
    'raisin',
    'fuchsia',
    'magenta',
    'indigo',
  ]

  // GOOD and BAD

  const bad = [
    'abominable',
    'abort',
    'abuse',
    'amiss',
    'annihilate',
    'annul',
    'asphyxiate',
    'assassinate',
    'atrocious',
    'attack',
    'awful',
    'axe',
    'bad',
    'banefulness',
    'beastly',
    'beguile',
    'betray',
    'bull',
    'bummer',
    'butcher',
    'careless',
    'cheesy',
    'compromise',
    'concoct',
    'corrupt',
    'crappy',
    'crime',
    'crimson',
    'crisis',
    'crucify',
    'cruddy',
    'crummy',
    'crush',
    'damage',
    'death',
    'deceive',
    'deface',
    'defective',
    'deficient',
    'deleteriousness',
    'delude',
    'desolate',
    'despoil',
    'destroy',
    'detriment',
    'devil',
    'diddly',
    'dismantle',
    'dispatch',
    'dissatisfactory',
    'dissemble',
    'disservice',
    'dissimulate',
    'distort',
    'distraction',
    'downer',
    'dreadful',
    'drown',
    'dump',
    'dupe',
    'electrocute',
    'evil',
    'end',
    'equivocate',
    'eradicate',
    'erase',
    'erroneous',
    'exaggerate',
    'execute',
    'exterminate',
    'extinguish',
    'extirpate',
    'fabricate',
    'fake',
    'fallacious',
    'falsify',
    'faulty',
    'fib',
    'finish',
    'force',
    'forswear',
    'frame',
    'fudge',
    'garbage',
    'garrote',
    'godawful',
    'grody',
    'gross',
    'grungy',
    'guillotine',
    'gut',
    'hang',
    'harm',
    'hit',
    'hurt',
    'icky',
    'ill',
    'immolate',
    'immorality',
    'impair',
    'impairment',
    'imperfect',
    'inadequate',
    'incorrect',
    'inferior',
    'infliction',
    'iniquity',
    'invent',
    'junky',
    'kill',
    'liquidate',
    'loss',
    'lousy',
    'lynch',
    'maim',
    'malign',
    'mar',
    'maraud',
    'marring',
    'massacre',
    'mischance',
    'mischief',
    'misfortune',
    'misguide',
    'misinform',
    'mislead',
    'misrepresent',
    'misspeak',
    'misstate',
    'misuse',
    'molest',
    'murder',
    'mutilate',
    'neutralize',
    'noxiousness',
    'nuke',
    'nullify',
    'obliterate',
    'outrage',
    'overdraw',
    'overturn',
    'palter',
    'perjure',
    'perniciousness',
    'pervert',
    'phony',
    'poison',
    'prejudice',
    'prevaricate',
    'problem',
    'quash',
    'quell',
    'raunchy',
    'ravage',
    'ravish',
    'raze',
    'rough',
    'ruin',
    'ruination',
    'sabotage',
    'sacrifice',
    'sad',
    'satan',
    'shatter',
    'sin',
    'sinfulness',
    'slaughter',
    'slay',
    'slipshod',
    'smash',
    'smother',
    'snuff',
    'stinking',
    'strangle',
    'substandard',
    'suffocate',
    'suppress',
    'synthetic',
    'torpedo',
    'trash',
    'trouble',
    'unacceptable',
    'unsatisfactory',
    'vandalism',
    'vaporize',
    'vice',
    'violance',
    'violate',
    'violence',
    'waste',
    'wax',
    'wickedness',
    'wreck',
    'wrong',
    'zap',
  ]

  const good = [
    'accomplishment',
    'achievement',
    'advance',
    'advantage',
    'arrival',
    'ascendancy',
    'asset',
    'attainment',
    'avail',
    'behalf',
    'benediction',
    'benefit',
    'blessed',
    'blessing',
    'blest',
    'blissful',
    'blithe',
    'boom',
    'boon',
    'break',
    'captivated',
    'cheerful',
    'chipper',
    'chirpy',
    'clover',
    'commonwealth',
    'consummation',
    'content',
    'contented',
    'convivial',
    'delight',
    'delighted',
    'ecstatic',
    'elated',
    'eminence',
    'exultant',
    'fame',
    'favor',
    'flourish',
    'fluke',
    'fortune',
    'fruition',
    'gain',
    'gay',
    'glad',
    'gleeful',
    'godsend',
    'gratified',
    'happiness',
    'health',
    'interest',
    'intoxicated',
    'jolly',
    'joyful',
    'joyous',
    'jubilant',
    'kismet',
    'laugher',
    'laughing',
    'light',
    'lively',
    'looking good',
    'love',
    'luckiness',
    'luxuriate',
    'maturation',
    'merry',
    'mirthful',
    'nugget',
    'opportunity',
    'overjoyed',
    'peaceful',
    'peppy',
    'perky',
    'playful',
    'pleasant',
    'pleased',
    'prize',
    'profit',
    'progress',
    'prosper',
    'prosperity',
    'realization',
    'relish',
    'reward',
    'satisfied',
    'savor',
    'savvy',
    'sensation',
    'serendipity',
    'service',
    'smile',
    'snap',
    'sparkling',
    'stroke',
    'success',
    'successfulness',
    'sunny',
    'thrilled',
    'thrive',
    'tickled',
    'tickled pink',
    'treasure',
    'triumph',
    'upbeat',
    'usefulness',
    'victory',
    'walkaway',
    'walkover',
    'weal',
    'wealth',
    'welfare',
    'well-being',
    'win',
    'windfall',
  ]

  // PSYCHO

  const egoism = [
    'i',
    'me',
    'personally',
    'my',
    'mine',
    'myself',
    'self',
    'ego',
  ]

  const altruism = [
    'you',
    'your',
    'yours',
    'we',
    'together',
  ]

  // BAD WORDS

  const wtf = [
    'God damn', 'Goddamn', 'anal', 'anus',
    'arse', 'ass', 'balls', 'ballsack',
    'bastard', 'biatch', 'bitch', 'bloody',
    'blow job', 'blowjob', 'bollock', 'bollok',
    'boner', 'boob', 'bugger', 'bum',
    'butt', 'buttplug', 'clitoris', 'cock',
    'coon', 'crap', 'cunt', 'damn',
    'dick', 'dildo', 'dyke',
    'fag', 'feck', 'felching', 'fellate',
    'fellatio', 'flange', 'fuck', 'fudge packer',
    'fudgepacker', 'hell', 'homo', 'jerk',
    'jizz', 'knob end', 'knobend', 'labia',
    'lmao', 'lmfao', 'muff', 'nigga',
    'nigger', 'omg', 'penis', 'piss',
    'poop', 'prick', 'pube', 'pussy',
    'queer', 'scrotum', 'sex',
    'sh1t', 'shit', 'slut', 'smegma',
    'spunk', 'tit', 'tosser', 'turd',
    'twat', 'vagina', 'wank', 'whore',
    'wtf',
  ]

  const result = {
    red: countWordsArray(red, lyrics),
    green: countWordsArray(green, lyrics),
    blue: countWordsArray(blue, lyrics),
    yellow: countWordsArray(yellow, lyrics),
    orange: countWordsArray(orange, lyrics),
    purple: countWordsArray(purple, lyrics),
    bad: countWordsArray(bad, lyrics),
    good: countWordsArray(good, lyrics),
    egoism: countWordsArray(egoism, lyrics),
    altruism: countWordsArray(altruism, lyrics),
    wtf: countWordsArray(wtf, lyrics),
  }
  return result
}
